#!/bin/bash

[ -z "$1" ] && exit 1

cat > $1.c << EOF

/************************************************************
 * dewox: $1
 *
 * Licensed under GPLv2.
 * ABSOLUTELY NO WARRANTY!
 *
 * Copyright (C) eXerigumo Clanjor (哆啦比猫/兰威举).
 ************************************************************/

#include "editor_decl.h"

void editor_$1_init()
{
	REGISTER_EDITOR("$1");
}

static void render(int w, int h)
{
}

static void hover(int x, int y, int w, int h)
{
}

static void click(int x, int y, int w, int h, int btn, int stt)
{
}

static void drag(int x, int y, int w, int h)
{
}

static void keypress(int key, int w, int h)
{
}

EOF

cat >> editors << EOF

	void editor_$1_init();
	editor_$1_init();
EOF

