#!/bin/bash

headername="__D_$(basename $1 .h | awk '$0=toupper($0)')_H"
cat > $1 << EOF

/************************************************************
 * dewox: $(basename $1)
 *
 * Licensed under GPLv2.
 * ABSOLUTELY NO WARRANTY!
 *
 * Copyright (C) eXerigumo Clanjor (哆啦比猫/兰威举).
 ************************************************************/

#ifndef $headername
#define $headername


#endif

EOF

